name: GitHub Actions Demo
on:
  push:
    branches:
    - main
    paths-ignore:
    - .github/**
  pull_request:
    branches:
    - main
  schedule:
  - cron: "15 6 * * 0"
  workflow_dispatch:

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Print event name
      run: echo "${{ github.event_name }}"
    - name: Print branch name
      run: echo "${{ github.ref }}"
    - name: List files
      run: tree
