name: Reuse other workflow

on: [workflow_dispatch]

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      who-to-greet: '@mattiassluis'

  use-output:
    needs: call-workflow
    runs-on: ubuntu-latest
    steps:
    - name: Echo time
      run: echo "Time of execution ${{ needs.call-workflow.outputs.current-time }}"
    
